### ISSUE TITLE
Не хватает инструкции как собрать и запустить

### ISSUE THREAD

**Issue by rukeba** [SergeyDomoslavkiy/SPA-GitHub-Searcer#1]
И в gulpfile нет default task - чтобы сразу собирать css и js

**Comment by SergeyDomoslavkiy** [comment]
проект уже собран. Запускать с папки  public

в gulpfile - есть таска "watch" - ее и запускаем для сборки

**Comment by rukeba** [comment]
> Запускать с папки public

Так как запускать?

**Comment by SergeyDomoslavkiy** [comment]
обновил доку

**Comment by SergeyDomoslavkiy** [comment]
Разобрались?

**Comment by rukeba** [comment]
Не понятно как запускать :)

Как запустить http server в этой папке?

Я конечно могу в папке public сделать такое:
`python -m SimpleHTTPServer 8000`
или прямо в IIS сделать сайт и замапить туда.

Хочется чтобы работал стандартный путь для node приложений:
`npm starts`
или 
`node server.js`

**Comment by SergeyDomoslavkiy** [comment]
я использую OpenServer с Веб-сервером Apache. Там все просто. В папке Domains создал новую директорию, назвал любым именем. В нее закинул все файлы с папки проекта public, запустил сервер и вуаля :)

**Comment by SergeyDomoslavkiy** [comment]
добавил server.js теперь с NodeJS будет все работать. Доку обновил

**Comment by SergeyDomoslavkiy** [comment]
доку обновил. Добавил версию на Backbone

**Comment by rukeba** [comment]
Но теперь получилось, что в проекте несколько package.json - это т.е. в каждой директории может быть свой node_modules — это недопустимо, бардак в проекте.

**Comment by SergeyDomoslavkiy** [comment]
исправил
