### ISSUE TITLE
А почему angular и его модули не в packages.json?

### ISSUE THREAD

**Issue by rukeba** [SergeyDomoslavkiy/SPA-GitHub-Searcer#2]
А сразу лежат в public/js?

**Comment by SergeyDomoslavkiy** [comment]
Я скопировал эти файлы с другого проекта.

**Comment by rukeba** [comment]
Это я понимаю. Но какие там версии? Как их потом обновлять? Зачем держать в проекте код, который можно ставить из npm? Почему вы тогда gulp не положили в проект, а ставите его через npm?

**Comment by SergeyDomoslavkiy** [comment]
Я Вас понял, да, мой косяк. Но, обновлять версии Angular нет необходимости, так как с каждой версией - с его основной сборки выбрасываются те или иные модуля (и переносятся в отдельные подключаемые файлы) для облегчения веса файла библиотеки. А это может затронуть и поломать работу нашего Веб-приложения, что конечно же, не желательно.
